# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run_db:
    cmd: docker-compose -f infra/docker/postgres/docker-compose.yml up -d
  run_server:
    cmd: air
  generate_migrations:
    cmds:
      - |
        echo "please enter the migration name:"
        read migration;
        atlas migrate diff ${migration} --env local --to "file://schema.sql";
  apply_migrations:
    cmd: atlas migrate apply --env local
  hash_migrations:
    cmd: atlas migrate hash --dir "file://internal/migrations"
