# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run_db:
    cmd: docker-compose -f infra/docker/postgres/docker-compose.yml up -d
  run_server:
    cmd: air
